import type { Dashboard } from '@/features/dashboards/dashboard-types'

export const MOCK_DASHBOARDS: Dashboard[] = [
  {
    id: 1,
    nome: 'BI Senac',
    icone: 'attach_money',
    url: 'https://app.powerbi.com/view?r=bi-senac',
    visivel: true,
    privacidade: 'privado',
    temporario: false,
    usuarioCadastrador: 'admin@silexcode.com',
    dataCriacao: '2024-01-15',
  },
  {
    id: 2,
    nome: 'Dashboard Seed 01',
    icone: 'bar_chart',
    url: 'https://app.powerbi.com/view?r=seed-01',
    visivel: true,
    privacidade: 'publico',
    temporario: false,
    usuarioCadastrador: 'admin@silexcode.com',
    dataCriacao: '2024-02-10',
  },
  {
    id: 3,
    nome: 'Dashboard Seed 02',
    icone: 'shopping_cart',
    url: 'https://app.powerbi.com/view?r=seed-02',
    visivel: false,
    privacidade: 'privado',
    temporario: true,
    dataExpiracaoInicial: '2025-01-01',
    dataExpiracaoFinal: '2025-12-31',
    usuarioCadastrador: 'admin@silexcode.com',
    dataCriacao: '2024-03-05',
  },
  {
    id: 4,
    nome: 'Dashboard Seed 03',
    icone: 'folder',
    url: 'https://app.powerbi.com/view?r=seed-03',
    visivel: true,
    privacidade: 'privado',
    temporario: true,
    dataExpiracaoInicial: '2025-06-01',
    dataExpiracaoFinal: '2025-09-30',
    usuarioCadastrador: 'maria@empresa.com',
    dataCriacao: '2024-04-20',
  },
  {
    id: 5,
    nome: 'Dashboard Seed 04',
    icone: 'insert_chart',
    url: 'https://app.powerbi.com/view?r=seed-04',
    visivel: true,
    privacidade: 'publico',
    temporario: false,
    usuarioCadastrador: 'joao@empresa.com',
    dataCriacao: '2024-05-12',
  },
  {
    id: 6,
    nome: 'Dashboard Seed 05',
    icone: 'analytics',
    url: 'https://app.powerbi.com/view?r=seed-05',
    visivel: false,
    privacidade: 'publico',
    temporario: false,
    usuarioCadastrador: 'admin@silexcode.com',
    dataCriacao: '2024-06-01',
  },
  {
    id: 7,
    nome: 'Dashboard Seed 06',
    icone: 'pie_chart',
    url: 'https://app.powerbi.com/view?r=seed-06',
    visivel: true,
    privacidade: 'privado',
    temporario: false,
    usuarioCadastrador: 'ana@empresa.com',
    dataCriacao: '2024-06-18',
  },
  {
    id: 8,
    nome: 'Dashboard Seed 07',
    icone: 'trending_up',
    url: 'https://app.powerbi.com/view?r=seed-07',
    visivel: true,
    privacidade: 'publico',
    temporario: true,
    dataExpiracaoInicial: '2025-03-01',
    dataExpiracaoFinal: '2025-06-30',
    usuarioCadastrador: 'carlos@empresa.com',
    dataCriacao: '2024-07-02',
  },
  {
    id: 9,
    nome: 'Dashboard Seed 08',
    icone: 'inventory',
    url: 'https://app.powerbi.com/view?r=seed-08',
    visivel: false,
    privacidade: 'privado',
    temporario: false,
    usuarioCadastrador: 'admin@silexcode.com',
    dataCriacao: '2024-07-22',
  },
  {
    id: 10,
    nome: 'Dashboard Seed 09',
    icone: 'groups',
    url: 'https://app.powerbi.com/view?r=seed-09',
    visivel: true,
    privacidade: 'privado',
    temporario: true,
    dataExpiracaoInicial: '2025-04-01',
    dataExpiracaoFinal: '2025-08-31',
    usuarioCadastrador: 'maria@empresa.com',
    dataCriacao: '2024-08-05',
  },
  {
    id: 11,
    nome: 'Dashboard Seed 10',
    icone: 'monitoring',
    url: 'https://app.powerbi.com/view?r=seed-10',
    visivel: true,
    privacidade: 'publico',
    temporario: false,
    usuarioCadastrador: 'joao@empresa.com',
    dataCriacao: '2024-08-19',
  },
  {
    id: 12,
    nome: 'Dashboard Seed 11',
    icone: 'account_balance',
    url: 'https://app.powerbi.com/view?r=seed-11',
    visivel: false,
    privacidade: 'privado',
    temporario: true,
    dataExpiracaoInicial: '2025-02-01',
    dataExpiracaoFinal: '2025-05-31',
    usuarioCadastrador: 'admin@silexcode.com',
    dataCriacao: '2024-09-01',
  },
  {
    id: 13,
    nome: 'Dashboard Seed 12',
    icone: 'storefront',
    url: 'https://app.powerbi.com/view?r=seed-12',
    visivel: true,
    privacidade: 'publico',
    temporario: false,
    usuarioCadastrador: 'ana@empresa.com',
    dataCriacao: '2024-09-15',
  },
  {
    id: 14,
    nome: 'Dashboard Seed 13',
    icone: 'local_shipping',
    url: 'https://app.powerbi.com/view?r=seed-13',
    visivel: true,
    privacidade: 'privado',
    temporario: false,
    usuarioCadastrador: 'carlos@empresa.com',
    dataCriacao: '2024-10-03',
  },
  {
    id: 15,
    nome: 'Dashboard Seed 14',
    icone: 'factory',
    url: 'https://app.powerbi.com/view?r=seed-14',
    visivel: false,
    privacidade: 'publico',
    temporario: true,
    dataExpiracaoInicial: '2025-07-01',
    dataExpiracaoFinal: '2025-10-31',
    usuarioCadastrador: 'maria@empresa.com',
    dataCriacao: '2024-10-20',
  },
  {
    id: 16,
    nome: 'Dashboard Seed 15',
    icone: 'school',
    url: 'https://app.powerbi.com/view?r=seed-15',
    visivel: true,
    privacidade: 'privado',
    temporario: false,
    usuarioCadastrador: 'admin@silexcode.com',
    dataCriacao: '2024-11-01',
  },
  {
    id: 17,
    nome: 'Dashboard Seed 16',
    icone: 'health_and_safety',
    url: 'https://app.powerbi.com/view?r=seed-16',
    visivel: true,
    privacidade: 'publico',
    temporario: true,
    dataExpiracaoInicial: '2025-01-15',
    dataExpiracaoFinal: '2025-04-15',
    usuarioCadastrador: 'joao@empresa.com',
    dataCriacao: '2024-11-12',
  },
  {
    id: 18,
    nome: 'Dashboard Seed 17',
    icone: 'engineering',
    url: 'https://app.powerbi.com/view?r=seed-17',
    visivel: false,
    privacidade: 'privado',
    temporario: false,
    usuarioCadastrador: 'ana@empresa.com',
    dataCriacao: '2024-11-28',
  },
  {
    id: 19,
    nome: 'Dashboard Seed 18',
    icone: 'real_estate_agent',
    url: 'https://app.powerbi.com/view?r=seed-18',
    visivel: true,
    privacidade: 'privado',
    temporario: true,
    dataExpiracaoInicial: '2025-05-01',
    dataExpiracaoFinal: '2025-11-30',
    usuarioCadastrador: 'carlos@empresa.com',
    dataCriacao: '2024-12-05',
  },
  {
    id: 20,
    nome: 'Dashboard Seed 19',
    icone: 'savings',
    url: 'https://app.powerbi.com/view?r=seed-19',
    visivel: true,
    privacidade: 'publico',
    temporario: false,
    usuarioCadastrador: 'admin@silexcode.com',
    dataCriacao: '2024-12-18',
  },
  {
    id: 21,
    nome: 'Dashboard Seed 20',
    icone: 'dashboard',
    url: 'https://app.powerbi.com/view?r=seed-20',
    visivel: false,
    privacidade: 'privado',
    temporario: true,
    dataExpiracaoInicial: '2025-08-01',
    dataExpiracaoFinal: '2025-12-31',
    usuarioCadastrador: 'maria@empresa.com',
    dataCriacao: '2025-01-02',
  },
]

export function getMockDashboards(): Dashboard[] {
  return MOCK_DASHBOARDS.map((dashboard) => {
    const creationDate = dashboard.dataCriacao
      ? `${dashboard.dataCriacao}T${String(8 + (dashboard.id % 12)).padStart(2, '0')}:${String((dashboard.id * 7) % 60).padStart(2, '0')}:00`
      : undefined

    const updateHour = 10 + (dashboard.id % 10)
    const updateDate = creationDate
      ? creationDate.replace(/T\d{2}:\d{2}:\d{2}/, `T${String(updateHour).padStart(2, '0')}:59:00`)
      : undefined

    return {
      ...dashboard,
      dataCriacao: creationDate,
      dataAtualizacao: updateDate,
      usuarioAtualizador: dashboard.usuarioAtualizador ?? dashboard.usuarioCadastrador,
    }
  })
}
