export const RBAC_ROLES = {
  ADMIN: 'REGRA_ADMIN',
  USUARIO: 'REGRA_USUARIO',
  DASHBOARD: 'REGRA_DASHBOARD',
  RELATORIO: 'REGRA_RELATORIO',
} as const

export const RBAC_PERMISSIONS = {
  CRIAR_USUARIO: 'PERMISSAO_CRIAR_USUARIO',
  ATUALIZAR_USUARIO: 'PERMISSAO_ATUALIZAR_USUARIO',
  EXCLUIR_USUARIO: 'PERMISSAO_EXCLUIR_USUARIO',
  CONCEDER_ACESSO_DASHBOARD: 'PERMISSAO_CONCEDER_ACESSO_DASHBOARD',
  CONCEDER_ACESSO_RELATORIO: 'PERMISSAO_CONCEDER_ACESSO_RELATORIO',
  CRIAR_DASHBOARD: 'PERMISSAO_CRIAR_DASHBOARD',
  ATUALIZAR_DASHBOARD: 'PERMISSAO_ATUALIZAR_DASHBOARD',
  EXCLUIR_DASHBOARD: 'PERMISSAO_EXCLUIR_DASHBOARD',
  CONCEDER_ACESSO_USUARIO: 'PERMISSAO_CONCEDER_ACESSO_USUARIO',
  CRIAR_RELATORIO: 'PERMISSAO_CRIAR_RELATORIO',
  ATUALIZAR_RELATORIO: 'PERMISSAO_ATUALIZAR_RELATORIO',
  EXCLUIR_RELATORIO: 'PERMISSAO_EXCLUIR_RELATORIO',
  CRIAR_CONEXAO: 'PERMISSAO_CRIAR_CONEXAO',
  ATUALIZAR_CONEXAO: 'PERMISSAO_ATUALIZAR_CONEXAO',
  EXCLUIR_CONEXAO: 'PERMISSAO_EXCLUIR_CONEXAO',
} as const

export const USER_RBAC = {
  menuRole: RBAC_ROLES.USUARIO,
  create: RBAC_PERMISSIONS.CRIAR_USUARIO,
  update: RBAC_PERMISSIONS.ATUALIZAR_USUARIO,
  delete: RBAC_PERMISSIONS.EXCLUIR_USUARIO,
  permissionsTabRole: RBAC_ROLES.ADMIN,
  grantDashboardAccess: RBAC_PERMISSIONS.CONCEDER_ACESSO_DASHBOARD,
  grantReportAccess: RBAC_PERMISSIONS.CONCEDER_ACESSO_RELATORIO,
  grantAccessPermissions: [
    RBAC_PERMISSIONS.CONCEDER_ACESSO_DASHBOARD,
    RBAC_PERMISSIONS.CONCEDER_ACESSO_RELATORIO,
  ],
} as const

export const DASHBOARD_RBAC = {
  menuRole: RBAC_ROLES.DASHBOARD,
  create: RBAC_PERMISSIONS.CRIAR_DASHBOARD,
  update: RBAC_PERMISSIONS.ATUALIZAR_DASHBOARD,
  delete: RBAC_PERMISSIONS.EXCLUIR_DASHBOARD,
  grantAccess: RBAC_PERMISSIONS.CONCEDER_ACESSO_USUARIO,
} as const

export const REPORT_RBAC = {
  menuRole: RBAC_ROLES.RELATORIO,
  create: RBAC_PERMISSIONS.CRIAR_RELATORIO,
  update: RBAC_PERMISSIONS.ATUALIZAR_RELATORIO,
  delete: RBAC_PERMISSIONS.EXCLUIR_RELATORIO,
  grantAccess: RBAC_PERMISSIONS.CONCEDER_ACESSO_RELATORIO,
} as const

export const CONNECTION_RBAC = {
  menuRole: RBAC_ROLES.RELATORIO,
  create: RBAC_PERMISSIONS.CRIAR_CONEXAO,
  update: RBAC_PERMISSIONS.ATUALIZAR_CONEXAO,
  delete: RBAC_PERMISSIONS.EXCLUIR_CONEXAO,
} as const

export const METRICS_RBAC = {
  menuRole: RBAC_ROLES.ADMIN,
} as const

export const JOBS_RBAC = {
  menuRole: RBAC_ROLES.ADMIN,
} as const
